---
title: "DSCI 522 Slides"
subtitle: "Reproducible and Trustworthy Data Science Workflow"
author: "Sky (Kehan) Sheng"
---

## Welcome

This site contains lecture and lab slides for DSCI 522 - Reproducible and Trustworthy Data Science Workflow, in section 001, for 2025W1.

## Instructor

**Sky (Kehan) Sheng**  
University of British Columbia  
[www.skysheng.io](https://www.skysheng.io)

## Available Slides

### Lectures

- [Lecture 1](lectures/lec1.html) - Introduction to Reproducible and Trustworthy Data Science Workflow
- [Lecture 2](lectures/lec2.html) - Conda-lock, Containerization, and Docker
- [Lecture 3](lectures/lec3.html) - Customizing and Building Containers
- [Lecture 4](lectures/lec4.html) - Containerizing Python Applications
- [Lecture 5](lectures/lec5.html) - Non-interactive scripts

### Labs

- [Lab 1 Introduction](labs/lab1-intro.html) - Introduction to reproducible workflows, lab policies, and getting started

### Cheatsheets

- [Conda & Conda-lock Cheatsheet](cheatsheets/cheatsheet_conda.html) - Quick reference for conda environment management and conda-lock
- [Docker & Docker Compose Cheatsheet](cheatsheets/cheatsheet_docker.html) - Quick reference for Docker containerization and Docker Compose

## License

This work is licensed under the MIT License.

